/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "media",
  theme: {
    extend: {
      colors: {
        surface1: "var(--surface-1)",
        surface2: "var(--surface-2)",
        plane: "var(--page-plane)",
        ink: "var(--text-primary)",
        ink2: "var(--text-secondary)",
        muted: "var(--text-muted)",
        gridline: "var(--gridline)",
        baseline: "var(--baseline)",
        series1: "var(--series-1)",
        series2: "var(--series-2)",
        series3: "var(--series-3)",
        series4: "var(--series-4)",
        series5: "var(--series-5)",
        series6: "var(--series-6)",
        series7: "var(--series-7)",
        series8: "var(--series-8)",
        divPos: "var(--diverging-pos)",
        divNeg: "var(--diverging-neg)",
        divMid: "var(--diverging-mid)",
        brandNavyDeep: "var(--brand-navy-deep)",
        navy: "var(--navy)",
        navySoft: "var(--navy-soft)",
        good: "var(--status-good)",
        warning: "var(--status-warning)",
        serious: "var(--status-serious)",
        critical: "var(--status-critical)",
        toneRedBg: "var(--tone-red-bg)",
        toneRedText: "var(--tone-red-text)",
        toneAmberBg: "var(--tone-amber-bg)",
        toneAmberText: "var(--tone-amber-text)",
        toneGreenBg: "var(--tone-green-bg)",
        toneGreenText: "var(--tone-green-text)",
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', "system-ui", "-apple-system", '"Segoe UI"', "sans-serif"],
      },
      boxShadow: {
        card: "var(--shadow-card)",
      },
    },
  },
  plugins: [],
};
